app/routes/forms/__init__.py
from .login import RegisterForm, LoginForm, TaskForm, SettingsForm

app/routes/forms/login.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, HiddenField
from wtforms.validators import DataRequired, EqualTo, Email

class RegisterForm(FlaskForm):
	email = StringField('Email', validators=[DataRequired("Please enter an email address"), Email("Please enter a valid email address")])
	password = PasswordField('Password', validators=[DataRequired(), EqualTo('password2', "Passwords do not match")])
	password2 = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password', "")])
	submit = SubmitField('Register')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired()], render_kw={"placeholder": "email@bambinito.co"})
    password = PasswordField('Password', validators=[DataRequired()], render_kw={"placeholder": "**********"})
    sremember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class TaskForm(FlaskForm):
	task_id = HiddenField('task_id')
	dept = StringField('Department', validators=[DataRequired()], render_kw={"placeholder": "COMP"})
	code = StringField('Code', validators=[DataRequired()], render_kw={"placeholder": "101"})
	crn = StringField('CRN', validators=[DataRequired()], render_kw={"placeholder": "98765"})
	term = StringField('Term', validators=[DataRequired()], render_kw={"placeholder": "Fall2034"})
	submit = SubmitField('Submit')
	delete = SubmitField('Delete')


class SettingsForm(FlaskForm):
	password = PasswordField('Current Password', validators=[DataRequired()])
	new_password = PasswordField(' New Password', validators=[DataRequired(), EqualTo('new_password2', "Passwords do not match")])
	new_password2 = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('new_password', "")])
	submit = SubmitField('Change Password')

app/__init__.py
from .app import configure, create_app, start

app/api/__init__.py
from .api import Api

api = Api()

app/app.py
import logging

from flask import Flask
from flask_bootstrap import Bootstrap
from vyper import v

from app.config import parser, settings
from app.util.vyper import setup_vyper
from app.util.logging import setup_logging

logger = logging.getLogger(__name__)

def configure(**overrides):
	logging.getLogger("requests").setLevel(level=logging.INFO)
	logging.getLogger("urllib3").setLevel(level=logging.INFO)
	logging.getLogger('vyper').setLevel(level=logging.WARNING)
	logging.getLogger('werkzeug').setLevel(level=logging.INFO)
	#logging.getLogger('flask').setLevel(level=logging.DEBUG)

	setup_vyper(parser, overrides)
	setup_logging()



def create_app():
	# falcon.API instances are callable WSGI apps
	app = Flask(__name__)
	bootstrap = Bootstrap(app)

	app.config.update(v.all_settings(uppercase_keys=True))

	from app.routes.auth import view
	app.register_blueprint(view)

	from app.routes.user import view
	app.register_blueprint(view)

	return app


def start():
	logger.info("Starting {}".format(settings.get("APP_NAME")))
	logger.info("Environment: {}".format(settings.get("ENV_NAME")))
	pass

app/routes/auth.py
import logging
import json
import requests
import datetime

from app.config import settings
from app.api import api

import functools
from .forms import RegisterForm, LoginForm
from flask import Blueprint, render_template, redirect, url_for, flash, session, g

view = Blueprint("auth", __name__)


@view.route("/", methods=["GET"])
def base():
	return render_template("index.html")


@view.route('/login', methods=['GET', 'POST'])
def login():
	if session.get('user_id') and session.get('token'):
		 return redirect(url_for('user.home', user_id = session['user_id']))

	form = LoginForm()
	if form.validate_on_submit():
		data = {
			"email": form.email.data,
			"password": form.password.data,
		}
		#r = requests.post(settings.get("API_URL")+"/login", data=json.dumps(data))
		r = api.login(body=data)

		if r.status_code == 202:
		#if True:
			return redirect(url_for('user.home', user_id = session['user_id']))
		else:
			flash((r.json().get('description') if not None else "Error whilst processing your request"))

	return render_template('auth.html', title='Sign In', form=form)


@view.route("/register", methods=["GET", "POST"])
def register():
	form = RegisterForm()
	if form.validate_on_submit():
		data = {
			"email": form.email.data,
			"password": form.password.data,
		}
		#r = requests.post(settings.get("API_URL")+"/register", data=json.dumps(data))
		r = api.register(body=data)

		if r.status_code == 201:
		#if True:
			return redirect(url_for('user.home', user_id = session['user_id']))
		else:
			flash((r.json().get('description') if not None else "Error whilst processing your request"))

	return render_template("auth.html", title='Register', form=form)


@view.route('/logout')
def logout():
	session.clear()
	return redirect(url_for('auth.base'))

#@view.before_app_request
def load_user():
	user_id = session.get('user_id')
	token = session.get('token')

	if user_id and token:
		return
	else:
		return redirect(url_for('auth.login'))


def login_required(view):
	@functools.wraps(view)
	def wrapped_view(**kwargs):
		if (session['user_id'] is None or session['token'] is None):
			session.clear()
			return redirect(url_for('auth.login'))
		if (session['last_login'] <= (datetime.datetime.utcnow() - datetime.timedelta(hours=24)).timestamp()):
			session.clear()
			return redirect(url_for('auth.login'))
			
		return view(**kwargs)

	return wrapped_view

app/routes/user.py
import logging
import json
import requests

from app.config import settings
from app.api import api
from .auth import login_required
from .forms import TaskForm, SettingsForm

from flask import Blueprint, render_template, redirect, url_for, flash, session

view = Blueprint("user", __name__, url_prefix='/user')

@view.route('/<string:user_id>', methods=['GET', 'POST'])
@login_required
def home(user_id):
	user = api.get('/users/' + user_id)
	if user.status_code == 403:
		return redirect(url_for('user.home', user_id=user_id))
	user = user.json()
	form = TaskForm()
	if form.validate_on_submit():
		body = {
			"course": {
				"dept": form.dept.data,
				"code": form.code.data,
				"crn": form.crn.data,
				"term": form.term.data
			},
			"email": user['email']
		}

		task_id = form.task_id.data
		if task_id == "new":
			r = api.post('/users/' + user_id + '/tasks', body=body)
		elif form.delete.data:
			r = api.delete('/users/' + user_id + '/tasks/' + task_id)
		else:
			r = api.put('/users/' + user_id + '/tasks/' + task_id, body=body)
		#print(r.json())
	#print("getting tasks")
	tasks = api.get('/users/' + user_id + '/tasks').json()
	#print(tasks)
	return render_template('home.html', title='Courses', user=user, tasks=tasks, form=form)


@view.route('/<string:user_id>/help', methods=['GET'])
@login_required
def help(user_id):
	user = {'id': user_id}
	return render_template('help.html', title="Help", user=user)


@view.route('/<string:user_id>/settings', methods=['GET', 'POST'])
@login_required
def settings(user_id):
	user = api.get('/users/' + user_id).json()
	form = SettingsForm()
	if form.validate_on_submit():
		body = {
			"email": user['email'],
			"password": form.password.data,
			"new_password": form.new_password.data
		}

		r = api.put('/users/' + user_id, body=body)

		if r.status_code == 200:
			flash('Successfully changed your password.')
		else:
			flash('Error whilst changing your password, please try again.')

	return render_template('settings.html', title="Settings", user=user, form=form)

@view.route('/<string:user_id>/settings/notifier/<string:user_email>', methods=['GET'])
@login_required
def notifier_test(user_id, user_email):
	body = {'email': user_email}
	r = api.post('/users/' + user_id + '/notifier', body=body)
	if r.status_code != 201:
		flash("There was an error processing your request. Please try again (later).")
	else:
		flash("Email notification created successfully!")
	
	return redirect(url_for('user.settings', user_id=user_id))

app/templates/auth.html
{% extends 'bootstrap/base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}
    {% if title %}{{ title }} - Minerva App{% else %}Minerva App{% endif %}
{% endblock %}

{% block styles %}
{{super()}}
	<style>
		body {
			padding: 40px;
		}
		.form {
			text-align: center;
		}
   </style>
{% endblock%}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
       	<div class="form">
          	<div class="row">
        			<div class="col-md-3"></div>
        			<div class="col-md-6 col-xs-12">
          			<h1>{{ title }}</h1>
            		{{ wtf.quick_form(form) }}
        			</div>
        			<div class="col-md-3"></div>
    				</div>
      	</div>
    </div>
{% endblock %}

app/templates/help.html
{% extends "user.html" %}


{% block styles %}
{{super()}}
	<style>
    h3 {
    	margin-top: 10px;
    	margin-bottom: 20px;
    }
    h4 {
    	margin-top: 15px;
    }
  </style>
{% endblock %}

{% block user_content %}
	<div class="container">
		<h3>Help</h3>
		<h4>Introduction</h4>
		<p>This is an app which will check available places in a course.
		Each course task will check every 3 minutes if a space is available and if there is, it will send you an email notification.</p>

		<h4>Create a task</h4>
		<p>In order to create a task, please click on the "Add Course" button on your home page.
		A window will pop-up with the required info to be filled in.
		The syntax must match the format shown as example but here is a quick recap:</p>
		<ul>
			<li>Department: must be the 4 letters of the course number (eg: INTD).</li>
			<li>Code: must be the 3 digit course number (eg: 123 if the class is called INTD123).</li>
			<li>CRN: the 5 digit CRN code of the class found on minerva.</li>
			<li>Term: Must be the term followed by the year (eg: Winter2045). Accepted terms: Fall, Winter, Summer.</li>
		</ul>

		<h4>Additional Information</h4>
		<p>If you need to register for different "modules" of the class (eg: lab, tutorial, conference), please create a task for each individual one of these. They have different CRNs and each task can only accept one CRN.
		Example: I need to register for COMP101 Lecture (12345) and Lab4 (67890). I will create one task for each.... You're not dumb, you'll figure it out.</p>
		<p>Please check that you do receive the app's email notification by trying a test email. This can be found in your Settings. This will unsure that the emails don't get block or spammed.</p>

		<h4>Disclaimer</h4>
		<p>This will not guarantee you a place in the course but from experience it works everytime.
		Usually minerva is updated at midnight so you have the best chance of receiving an email aroung that time althought again, it can happen at any time.</p>
		<p>Under the current version, this app uses VSB to get the course data unauthenticated. However, it is believed that VSB has a small latency in it's data updates compared to Minerva. It is thus highly possible that once a space opens up on a class, VSB will only have the updated information up to a couple minutes afterwards. It has thus far nerver been an issue...</p>
		<p>It is very probable that this app has bugs and might not work. If you find anything or you would like to make suggestions/contributions, please contact <a href = "mailto: bambinito.dev@gmail.com">bambinito.dev@gmail.com</a> or it's very likely you know who I am personally so you can contact me anyway you feel like.
		By the way, this app uses an API available at api.minerva.bambinito.co. You're more than welcome to integrate with it. Please contact me and I'll be more than happy to help.</p>

		<h5>Enjoy!</h5>
	</div>
{% endblock %}

app/templates/home.html
{% extends "user.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
{{super()}}
	<style>
    .btn {
    	margin: 10px;
    }
    h2 {
    	margin-top: 5px;
    	margin-bottom: 15px;
    }
    .modal-content {
		  background-color: #fefefe;
		  margin: 15% auto;
		  padding: 20px;
		  border: 1px solid #888;
		  width: 80%;
		}
		.modal {
		  display: none;
		  position: fixed; 
		  z-index: 1; 
		  left: 0;
		  top: 0;
		  width: 100%; 
		  height: 100%; 
		  overflow: auto; 
		  background-color: rgb(0,0,0); 
		  background-color: rgba(0,0,0,0.4);
		}
    .modal-backdrop.in {
      opacity: 0;
    }

   </style>
{% endblock%}

{% block scripts %}
{{super()}}
	<script>
		$('#course_modal').on('show.bs.modal', function (event) {
		  var button = $(event.relatedTarget) // Button that triggered the modal
		  var task_id = button.data('id') // Extract info from data-* attributes
      //console.log(task_id)
      //console.log(button)
      var modal = $(this)

      if (task_id == "new") {
        var dept = ""
        var code = ""
        var crn = ""
        var term = ""
        var button_value = "Create"
        var show_button = true
        modal.find('.modal-body input#delete').hide()
      }
      else {
        var dept = button[0].cells[0].innerText
        var code = button[0].cells[1].innerText
        var crn = button[0].cells[2].innerText
        var term = button[0].cells[3].innerText
        var button_value = "Edit"
        modal.find('.modal-body input#delete').show()
        //console.log(dept)
      }
		  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
		  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      //console.log(modal.find('.modal-body input#delete'))
      modal.find('.modal-body input#task_id').val(task_id)
		  modal.find('.modal-body input#dept').val(dept)
      modal.find('.modal-body input#code').val(code)
      modal.find('.modal-body input#crn').val(crn)
      modal.find('.modal-body input#term').val(term)
      modal.find('.modal-body input#submit').val(button_value)
		})
	</script>
{% endblock %}

{% block user_content %}
<div class="container">
  		<button type="button" class="btn btn-default" data-id="new" data-toggle="modal" data-target="#course_modal">Add Course</button>
  </div>

    <div class="container">
   		<table class="table table-hover" id="course_table" style="width:100%">
			<thead><tr>
    			<th>Department</th>
    			<th>Course</th>
    			<th>CRN</th>
    			<th>Term</th>
    			<th>Active</th>
  			</tr></thead>

        <tbody>
  			{% for task in tasks %}
  			<tr data-id="{{task.id}}" data-toggle="modal" data-target="#course_modal">
    			<td>{{ task.course.dept }}</td>
    			<td>{{ task.course.code }}</td>
    			<td>{{ task.course.crn }}</td>
    			<td>{{ task.course.term }}</td>
    			<td>{{ task.active }}</td>
  			</tr>
  			{% endfor %}
        </tbody>
  		</table>
  	</div>

  	<div class="modal" id="course_modal" data-backdrop="false" role="dialog" tabindex="-1">
      <div class="modal-dialog">
    		<div class="modal-content">
    			<div class="modal-body">
  	  			<button type="button" class="close" data-dismiss="modal">
  	  				<span aria-hidden="true">&times;</span>
  	  			</button>
  	  			<h2>Course</h2>
  	  			<div class="form">
  	  				{{ wtf.quick_form(form) }}
  	  			</div>
  				</div>
    		</div>
      </div>
  	</div>
{% endblock %}

app/templates/index.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    Minerva App
{% endblock %}

{% block styles %}
{{super()}}
	<style>
		body {
			padding: 40px;
		}
    .intro {
    	padding: 40px 15px;
  		text-align: center;
    }
    .buttons {
    	padding: 10px;
    }
    .btn {
    	margin: 5px 15px;
    }
   </style>
{% endblock%}

{% block content%}
    <div class="container">
    	<div class="intro">
       	<h1>Welcome to the Minerva app</h1>
				<p class="lead">This is the app to get you a place in a class</p>
				<div class="buttons">
					<a class="btn btn-default" href="{{ url_for('auth.login') }}" role="button">Login</a>
					<a class="btn btn-default" href="{{ url_for('auth.register') }}" role="button">Register</a>
				</div>
			</div>
    </div>
{% endblock %}

app/templates/settings.html
{% extends "user.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
{{super()}}
	<style>
    h3 {
    	margin-top: 10px;
    	margin-bottom: 10px;
    }
    .btn {
    	margin-top: 10px;
    	margin-bottom: 20px;
    	margin-left: 10px;
    }
  </style>
{% endblock %}


{% block user_content %}
	<div class="container">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
          {% for message in messages %}
          <div class="alert alert-info" role="alert">{{ message }}</div>
          {% endfor %}
      {% endif %}
      {% endwith %}
  </div>

  <div class="container">
  		<h3>Test Email</h3>
  		<p>This is a button to test the email notifier. It will send you a test notification to your account's email.</p>
  		<a role="button" href="{{ url_for('user.notifier_test', user_id=user.id, user_email=user.email) }}" class="btn btn-default">Email Test</a>
  </div>

  <div class="container">
  	<div class="form">
    	<h3>Change Password</h3>
      {{ wtf.quick_form(form) }}
    </div>
  </div>

  <div class="container">
  	<h3>Additional settings</h3>
  	<p>We do not currently have a feature to change the email associated with the account.
  	Please create a new account if you'd like to do so.</p>
  </div>
{% endblock %}

app/templates/user.html
{% extends 'bootstrap/base.html' %}


{% block title %}
    {% if title %}{{ title }} - Minerva App{% else %}Minerva App{% endif %}
{% endblock %}


{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
    		<!-- Brand and toggle get grouped for better mobile display -->
    		<div class="navbar-header">
      			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#user-navbar" aria-expanded="false">
        			<span class="sr-only">Toggle navigation</span>
       				<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
        			<span class="icon-bar"></span>
      			</button>
     			 <a class="navbar-brand" href="{{ url_for('user.home', user_id=user.id) }}">Minerva</a>
    		</div>
    		<div class="collapse navbar-collapse" id="user-navbar">
    			<ul class="nav navbar-nav">
        			<li><a href="{{ url_for('user.help', user_id=user.id) }}">Help</a></li>
        		</ul>
      			<ul class="nav navbar-nav navbar-right">
        			<li><a href="{{ url_for('user.settings', user_id=user.id) }}">Settings</a></li>
        			<li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        		</ul>
        	</div>
        </div>
    </nav>
{% endblock %}

{% block content %}
	{% block user_content %}

  {% endblock %}
{% endblock %}